baseURL = "https://kollee.github.io/"
languageCode = "en-us"
title = "TILT"

theme = "hyde"

[Menus]
  main = [
      #{Name = "Github", URL = "https://github.com/kollee/"},
      #{Name = "LinkedIn", URL = "https://www.linkedin.com/in/username/"}
  ]

[params]
    subtitle = "**T**hings **I** **L**earned **T**oday!"
    description = "Things I Learned Today - Mostly about Information Security, Malware Analysis, Digital Forensics & Incident Response"